### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by MadKoTik** [chilyashev/AfterburnerMonitor#2]
When connected, it gives out - "the input string had the wrong format"

+

Could you make it minimized to tray?

**Comment by mchilyashev** [comment]
Hi, 

If you are still unsuccessful in trying to make this work, I'll need more details in order to fix the issue.  Where are you seeing this message? How is the Arduino connected to the computer?

**Comment by chilyashev** [comment]
Hi,

If you are still unsuccessful in trying to make this work, I'll need more details in order to fix the issue. Where are you seeing this message? How is the Arduino connected to the computer?

Minimizing to tray is really easy to implement. I might get to it some day, but if you are interested, you can try to do it yourself.

**Comment by EniSy** [comment]
I have the same issue with "the input string had the wrong format"
```

Port: COM1
'GUIThing.vshost.exe' (CLR v4.0.30319: GUIThing.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_ru_b77a5c561934e089\mscorlib.resources.dll'. Module was built without symbols.
Exception thrown: 'System.FormatException' in mscorlib.dll
The thread 0x1228 has exited with code 0 (0x0).
Входная строка имела неверный формат.
The thread 0x1a90 has exited with code 0 (0x0).
The thread 0x1864 has exited with code 0 (0x0).
The program '[6748] GUIThing.vshost.exe' has exited with code 0 (0x0).
```

**Comment by chilyashev** [comment]
Hi, what is the Arduino sending to the program? The only place with String.Format is the parsing of the data from the Arduino. 

Go to MainForm.cs and put a logging statement where the parsing is done ([around line 225](https://github.com/chilyashev/AfterburnerMonitor/blob/master/GUIThing/MainForm.cs#L225)).
Something like `Debug.WriteLine("Got {0} from Arduino", str);` should give you an idea of what's coming from the device.

Since it works correctly on four separate instances for me, I can't do much more to help you.

**Comment by chilyashev** [comment]
Ok, I got it. Do you have Afterburner running? Something's wrong with either your MSI Afterburner install or its dev dependencies. I've tried it on four different computers with different Arduinos without an issue. 

I've pushed a potential fix that at least won't crash the app if there's some bs returned from the lib.

If you want to continue debugging it, paste some of the debug output.
